services:
  haproxy:
    container_name: pctq-prod-hz-haproxy
    image: itcommunity/haproxy-frontend-prod:1.0.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
    tmpfs:
      - /run/haproxy:uid=999,gid=999,mode=0770
      - /var/lib/haproxy:uid=999,gid=999,mode=0750
    networks:
      pctq-prod-hz-net:
        ipv4_address: 172.25.0.2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    read_only: true
    security_opt:
      - no-new-privileges:true

networks:
  pctq-prod-hz-net:
    external: true
