version: "3.9"

services:
  haproxy:
    container_name: pctq-prod-hz-haproxy
    image: itcommunity/punctiq:prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - haproxy_config:/etc/haproxy
    tmpfs:
      - /run/haproxy
      - /var/lib/haproxy
    networks:
      pctq-prod-hz-net:
        ipv4_address: 172.25.0.2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    read_only: true
    security_opt:
      - no-new-privileges:true

volumes:
  haproxy_config:

networks:
  pctq-prod-hz-net:
    external: true
