version: "3.9"

services:
  haproxy:
    container_name: pctq-prod-hz-haproxy
    image: itcommunity/punctiq:prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - haproxy_config:/etc/haproxy
    networks:
      pctq-prod-hz-net:
        ipv4_address: 172.28.1.10
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    read_only: true
    security_opt:
      - no-new-privileges:true
    pull_policy: always  # Ensure the latest image is always pulled

volumes:
  haproxy_config:

networks:
  pctq-prod-hz-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.1.0/24
